# Semi-automatic draft seeder for .planning/test-matrix.yaml from codebase maps.
param(
    [string]$OutFile = '.planning/test-matrix.draft.yaml',
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$StructureFile = Join-Path $RepoRoot '.planning/codebase/STRUCTURE.md'
$TestingFile = Join-Path $RepoRoot '.planning/codebase/TESTING.md'
$OutPath = if ([System.IO.Path]::IsPathRooted($OutFile)) { $OutFile } else { Join-Path $RepoRoot $OutFile }

function Write-Step([string]$Message) {
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Get-AdapterModules([string]$Content, [string]$Family) {
    $pattern = "data-generator-$Family-([a-z0-9-]+)"
    [regex]::Matches($Content, $pattern) |
        ForEach-Object { $_.Groups[1].Value } |
        Sort-Object -Unique
}

function Get-TestClassNames([string]$Content) {
    [regex]::Matches($Content, '\b([A-Z][A-Za-z0-9]+(?:Tests|Test|IT))\b') |
        ForEach-Object { $_.Groups[1].Value } |
        Sort-Object -Unique
}

function Find-LinkedTest([string]$Adapter, [string[]]$TestNames) {
    foreach ($name in $TestNames) {
        if ($name -match $Adapter -or ($Adapter -eq 'database' -and $name -match 'Jdbc|Pipeline|Chunked')) {
            return $name
        }
    }
    return $null
}

Write-Step "Generating test matrix draft from codebase maps"

if (-not (Test-Path $StructureFile)) { throw "Missing $StructureFile" }
if (-not (Test-Path $TestingFile)) { throw "Missing $TestingFile" }

if ((Test-Path $OutPath) -and -not $Force) {
    throw "Draft file already exists at $OutPath. Pass -Force to overwrite."
}

$structure = Get-Content -Raw $StructureFile
$testing = Get-Content -Raw $TestingFile
$testNames = Get-TestClassNames $testing

$rows = New-Object System.Collections.Generic.List[string]
$schema = @"
schema:
  description: >
    Draft matrix generated by scripts/generate-test-matrix-draft.ps1. Review before merging
    into .planning/test-matrix.yaml (human-curated source of truth).
  columns:
    id: Stable row identifier.
    capability: Capability-first name.
    adapter: Adapter kind.
    test_types: Test categories.
    owner_module: Owning Maven module.
    status: covered | partial | pending | skipped-conditional.
    linked_tests: Maven class or Playwright spec#title.
    notes: Operator notes.
  status_values:
    - covered
    - partial
    - pending
    - skipped-conditional

rows:
"@

foreach ($family in @('reader', 'writer', 'iterator')) {
    foreach ($adapter in (Get-AdapterModules $structure $family)) {
        $module = "data-generator-$family-$adapter"
        $id = "$family-$adapter"
        $linked = Find-LinkedTest $adapter $testNames
        $status = if ($linked) { 'partial' } else { 'pending' }
        $linkedYaml = if ($linked) { "[$linked]" } else { '[]' }
        $rows.Add(@"
  - id: $id
    capability: $id
    adapter: $adapter
    test_types: [integration]
    owner_module: $module
    status: $status
    linked_tests: $linkedYaml
    notes: Draft row from STRUCTURE.md ($family adapter).
"@)
    }
}

$rows.Add(@"
  - id: calcite-pipeline-chunked
    capability: calcite-pipeline-chunked
    adapter: chunked
    test_types: [integration]
    owner_module: data-generator-calcite
    status: partial
    linked_tests: [ChunkedPipelineTests]
    notes: Draft row from TESTING.md reference.
"@)

$rows.Add(@"
  - id: console-api-templates
    capability: console-api-templates
    adapter: console-api
    test_types: [unit, e2e]
    owner_module: data-generator-service
    status: partial
    linked_tests: [ConsoleTemplateControllerTest]
    notes: Draft console API row.
"@)

$draft = $schema + "`n" + ($rows -join "`n")
Set-Content -Path $OutPath -Value $draft -Encoding utf8NoBOM
Write-Host "Draft written to $OutPath"
Write-Host "Review the draft and merge approved rows into .planning/test-matrix.yaml before commit." -ForegroundColor Yellow
